"use client";

import { useState } from "react";
import { Sparkles, Loader2, Database, Settings, FileText, Info, BookOpen, Terminal, ChevronDown, ChevronUp, ClipboardCopy, CheckCheck } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

const CCAT_SYLLABUS: Record<string, { section: string; books: string[] }> = {
    "Data Engineering & Big Data": {
        section: "BDA",
        books: ["Designing Data-Intensive Applications", "Fundamentals of Data Engineering"]
    },
    "Machine Learning": {
        section: "BDA",
        books: ["Pattern Recognition and Machine Learning", "Hands-On Machine Learning"]
    },
    "Deep Learning & AI": {
        section: "BDA",
        books: ["Deep Learning (Goodfellow)", "Artificial Intelligence: A Modern Approach"]
    },
    "Data Warehousing & Mining": {
        section: "BDA",
        books: ["Data Mining: Concepts and Techniques"]
    },
    "Statistics & Probability": {
        section: "BDA",
        books: ["Introduction to Probability and Statistics"]
    },
    "Database Management": {
        section: "BDA",
        books: ["Database System Concepts (Silberschatz)"]
    },
    "Cloud Computing": {
        section: "BDA",
        books: ["Cloud Computing: Concepts, Technology & Architecture"]
    },
    "Programming & Python": {
        section: "BDA",
        books: ["Python Crash Course", "Fluent Python"]
    },
    "Data Visualization": {
        section: "BDA",
        books: ["The Visual Display of Quantitative Information"]
    },
    "Algorithms & Data Structures": {
        section: "BDA",
        books: ["Introduction to Algorithms (CLRS)"]
    }
};

const SUBJECTS = Object.keys(CCAT_SYLLABUS);

interface QuestionGeneratorProps {
    onGenerationSuccess?: () => void;
}

export default function QuestionGenerator({ onGenerationSuccess }: QuestionGeneratorProps) {
    const { user } = useAuth();
    const [subject, setSubject] = useState(SUBJECTS[0]);
    const [count, setCount] = useState<number>(5);
    const [useReferenceBooks, setUseReferenceBooks] = useState<boolean>(true);
    const [customPrompt, setCustomPrompt] = useState("");
    const [pastedJson, setPastedJson] = useState("");
    const [status, setStatus] = useState<'idle' | 'seeding' | 'success' | 'error'>('idle');
    const [loadingMessage, setLoadingMessage] = useState("");
    const [errorMessage, setErrorMessage] = useState("");
    const [copied, setCopied] = useState(false);

    const handleCopyPrompt = () => {
        navigator.clipboard.writeText(previewPrompt);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSeedQuestions = async () => {
        if (!pastedJson.trim()) {
            setErrorMessage("Please paste the JSON generated by Gemini first.");
            setStatus("error");
            return;
        }

        setStatus("seeding");
        setErrorMessage("");
        setLoadingMessage("Parsing JSON and seeding to database...");

        try {
            let parsedQuestions;
            try {
                // Try parsing the text (handle if user pasted markdown block)
                const cleanedJsonText = pastedJson.replace(/```json/g, '').replace(/```/g, '').trim();
                parsedQuestions = JSON.parse(cleanedJsonText);
                
                if (!Array.isArray(parsedQuestions)) {
                     // Try wrapping in array if it is a single object
                     if (typeof parsedQuestions === 'object') {
                         parsedQuestions = [parsedQuestions];
                     } else {
                         throw new Error("Parsed JSON must be an array of questions.");
                     }
                }
            } catch (e: any) {
                throw new Error("Invalid JSON format. Please make sure you copied the exact JSON array output from Gemini.");
            }

            if (!user) {
                throw new Error("You must be logged in as an admin to perform this action.");
            }
            
            const token = await user.getIdToken();

            const response = await fetch('/api/admin/seed-questions', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({
                    subject,
                    section: CCAT_SYLLABUS[subject]?.section,
                    questions: parsedQuestions
                }),
            });

            const data = await response.json();

            if (!response.ok || !data.success) {
                throw new Error(data.error || "Failed to seed questions.");
            }

            setStatus("success");
            setLoadingMessage(`Successfully seeded ${data.count} questions!`);
            setPastedJson(""); // clear on success
            
            if (onGenerationSuccess) {
                onGenerationSuccess();
            }

            setTimeout(() => {
                setStatus("idle");
                setLoadingMessage("");
            }, 3000);

        } catch (error: any) {
            setStatus("error");
            setErrorMessage(error.message || "An unexpected error occurred.");
        }
    };

    const previewPrompt = `You are a highly advanced C-DAC C-CAT exam compilation AI agent. Your task is to generate exactly ${count} multiple-choice questions for the subject: "${subject}".

CRITICAL CONSTRAINTS:
1. Every item must be a classic MCQ containing EXACTLY 4 options (labeled A, B, C, D).
2. Exactly ONE option must be marked as correct ("is_correct": true), and three must be false.
3. You must provide a clean, readable text value in "question_text" and an HTML wrapped equivalent in "question_html" (use <code>, <pre>, or formatting if snippet logic is involved). Do the same for options and explanations.
4. "question_type" must strictly be "mcq".
5. The "branch" attribute must act as the Section delimiter. Categorize it explicitly as "${CCAT_SYLLABUS[subject]?.section || "Section A"}".
6. Generate a short, LeetCode style title (max 3-4 words) for the question in the "title" field (e.g. "Two Sum", "Pointer Arithmetic", "Switch Case Output").
7. IMPORTANT FOR CODE: When a question contains code, strictly format the code inside <pre><code>...</code></pre> tags in the "question_html" field with proper line breaks and indentation so it looks beautiful and readable.
8. Adhere strictly to this additional custom administrative tuning directive: ${customPrompt || 'None'}
${useReferenceBooks && CCAT_SYLLABUS[subject]?.books?.length > 0 ? `7. BASE YOUR CONTENT STRICTLY ON THESE OFFICIAL REFERENCE BOOKS:\n- ${CCAT_SYLLABUS[subject].books.join('\n- ')}` : ''}

REQUIRED JSON SCHEMA (Output MUST be an array of objects structured exactly like this):
[
  {
    "title": "string (max 3-4 words)",
    "question_text": "string",
    "question_html": "string (with proper <pre><code> formatting for code)",
    "subject": "${subject}",
    "topic": "string (specific topic)",
    "year": "2026",
    "branch": "${CCAT_SYLLABUS[subject]?.section || "Section A"}",
    "question_label": "string",
    "question_type": "mcq",
    "options": [
      {
        "label": "A",
        "text_html": "string",
        "is_correct": boolean
      },
      ... (exactly 4 options)
    ],
    "explanation_text": "string",
    "explanation_html": "string",
    "tags": ["string"]
  }
]

Output your result strictly as a clean JSON array adhering to the requested schema. Do not include extra text before or after the JSON.`;

    return (
        <div className="bg-white dark:bg-zinc-950 p-6 rounded-2xl border border-gray-200 dark:border-zinc-800 shadow-sm">
            <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-purple-100 dark:bg-purple-900/30 rounded-xl">
                    <Sparkles className="w-6 h-6 text-purple-600 dark:text-purple-400" />
                </div>
                <div>
                    <h2 className="text-xl font-bold text-gray-900 dark:text-white">AI Question Generator (Manual Mode)</h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Generate prompt, paste Gemini JSON, and seed</p>
                </div>
            </div>

            <div className="space-y-6">
                {/* 1. Configuration Section */}
                <div className="space-y-4">
                    <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider">1. Configure Prompt</h3>
                    
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5 flex items-center gap-2">
                            <FileText className="w-4 h-4 text-gray-400" /> Subject
                        </label>
                        <select
                            value={subject}
                            onChange={(e) => setSubject(e.target.value)}
                            disabled={status === 'seeding'}
                            className="w-full px-4 py-2.5 bg-gray-50 dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all dark:text-white disabled:opacity-50"
                        >
                            {SUBJECTS.map((sub) => (
                                <option key={sub} value={sub}>{sub}</option>
                            ))}
                        </select>
                    </div>

                    {subject && CCAT_SYLLABUS[subject] && (
                        <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-xl border border-blue-100 dark:border-blue-900/50">
                            <div className="flex items-start gap-3">
                                <Info className="w-5 h-5 text-blue-500 mt-0.5" />
                                <div>
                                    <h4 className="text-sm font-bold text-blue-900 dark:text-blue-100">
                                        {CCAT_SYLLABUS[subject].section}
                                    </h4>
                                    <div className="mt-2 space-y-1">
                                        <p className="text-sm text-blue-800 dark:text-blue-200 font-semibold flex items-center gap-2">
                                            <BookOpen className="w-4 h-4" /> Recommended Books
                                        </p>
                                        <ul className="list-disc list-inside text-xs text-blue-700 dark:text-blue-300 ml-1">
                                            {CCAT_SYLLABUS[subject].books.map((book, i) => (
                                                <li key={i}>{book}</li>
                                            ))}
                                        </ul>
                                    </div>
                                    <label className="flex items-center gap-2 mt-3 text-sm text-blue-800 dark:text-blue-200 cursor-pointer">
                                        <input 
                                            type="checkbox" 
                                            checked={useReferenceBooks} 
                                            onChange={(e) => setUseReferenceBooks(e.target.checked)}
                                            disabled={status === 'seeding'}
                                            className="rounded border-blue-300 text-blue-600 focus:ring-blue-500 bg-white dark:bg-zinc-900"
                                        />
                                        Include reference books as context for AI Generation
                                    </label>
                                </div>
                            </div>
                        </div>
                    )}

                    <div>
                        <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5 flex items-center gap-2">
                            <Settings className="w-4 h-4 text-gray-400" /> Count (1-50)
                        </label>
                        <input
                            type="number"
                            min="1"
                            max="50"
                            value={count}
                            onChange={(e) => setCount(parseInt(e.target.value) || 1)}
                            disabled={status === 'seeding'}
                            className="w-full px-4 py-2.5 bg-gray-50 dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all dark:text-white disabled:opacity-50"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5">
                            Custom Instructions (Optional)
                        </label>
                        <textarea
                            value={customPrompt}
                            onChange={(e) => setCustomPrompt(e.target.value)}
                            disabled={status === 'seeding'}
                            placeholder="e.g., Focus heavily on pointers and pointer arithmetic..."
                            className="w-full px-4 py-3 bg-gray-50 dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all resize-none h-24 dark:text-white disabled:opacity-50"
                        />
                    </div>
                </div>

                <div className="h-px bg-gray-200 dark:bg-zinc-800 my-4"></div>

                {/* 2. Prompt Generation & Copy */}
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                        <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider">2. Copy Prompt & Ask Gemini</h3>
                        <button 
                            onClick={handleCopyPrompt}
                            className="flex items-center gap-2 px-3 py-1.5 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 rounded-lg text-sm font-semibold hover:bg-purple-200 dark:hover:bg-purple-900/50 transition-colors"
                        >
                            {copied ? <CheckCheck className="w-4 h-4" /> : <ClipboardCopy className="w-4 h-4" />}
                            {copied ? "Copied!" : "Copy Prompt"}
                        </button>
                    </div>
                    
                    <div className="border border-gray-200 dark:border-zinc-800 rounded-xl overflow-hidden">
                        <div className="p-4 bg-gray-50 dark:bg-zinc-900">
                            <pre className="text-xs text-gray-600 dark:text-gray-400 whitespace-pre-wrap font-mono leading-relaxed max-h-60 overflow-y-auto">
                                {previewPrompt}
                            </pre>
                        </div>
                    </div>
                </div>

                <div className="h-px bg-gray-200 dark:bg-zinc-800 my-4"></div>

                {/* 3. Paste JSON and Seed */}
                <div className="space-y-4">
                    <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider">3. Paste JSON & Seed</h3>
                    
                    <div>
                        <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1.5 flex items-center gap-2">
                            <Terminal className="w-4 h-4 text-gray-400" /> Paste Gemini JSON Response
                        </label>
                        <textarea
                            value={pastedJson}
                            onChange={(e) => setPastedJson(e.target.value)}
                            disabled={status === 'seeding'}
                            placeholder="[ { ... }, { ... } ]"
                            className="w-full px-4 py-3 bg-gray-50 dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none transition-all resize-none h-40 dark:text-white font-mono text-sm disabled:opacity-50"
                        />
                    </div>

                    {/* Status Messages */}
                    {status === 'error' && (
                        <div className="p-3 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900/50 rounded-lg text-red-600 dark:text-red-400 text-sm font-medium">
                            {errorMessage}
                        </div>
                    )}
                    {status === 'success' && (
                        <div className="p-3 bg-green-50 dark:bg-green-950/30 border border-green-200 dark:border-green-900/50 rounded-lg text-green-600 dark:text-green-400 text-sm font-medium flex items-center gap-2">
                            <Database className="w-4 h-4" />
                            {loadingMessage}
                        </div>
                    )}

                    <button
                        onClick={handleSeedQuestions}
                        disabled={status === 'seeding' || !pastedJson.trim()}
                        className="w-full flex items-center justify-center gap-2 px-6 py-3.5 bg-green-600 hover:bg-green-700 text-white font-bold rounded-xl transition-all shadow-lg hover:shadow-green-500/25 hover:-translate-y-0.5 disabled:opacity-70 disabled:hover:translate-y-0 disabled:cursor-not-allowed"
                    >
                        {status === 'seeding' ? (
                            <>
                                <Loader2 className="w-5 h-5 animate-spin" />
                                {loadingMessage}
                            </>
                        ) : (
                            <>
                                <Database className="w-5 h-5" />
                                Seed Questions
                            </>
                        )}
                    </button>
                </div>
            </div>
        </div>
    );
}
